#!/bin/sh

SMS2GRAM_DIR="/opt/root/sms2gram"

rm -f "/opt/bin/sms2gram"
rm -f "/opt/var/log/sms2gram.log"
rm -f "/opt/etc/ndm/sms.d/01-sms2gram.sh"
rm -f "/opt/etc/ndm/ifipchanged.d/01-sms2gram.sh"
rm -f "/opt/etc/ndm/ifip6changed.d/01-sms2gram.sh"

exit 0
